// Single source of truth for cards on /blog.
// To add a post: drop a BlogPost<Slug>.jsx, register a <Route> in main.jsx,
// and append an entry here. Cards on /blog sort by `date` (ISO, descending).

export const blogPosts = [
  {
    slug: 'voice-system-downtime-playbook',
    route: '/blog/voice-system-downtime-playbook',
    title: 'When Your Voice System Goes Silent: A Downtime Playbook for Service Businesses — Borne Systems Blog',
    excerpt: 'Automation does not fail loudly. It fails quietly, one setting at a time, until customers start to fall through. Here is the first-hour playbook, the backup plan you set up before the outage, and the weekly test that catches silent failures.',
    tag: 'Maintenance',
    date: '2026-08-04',
    kind: 'post',
  },
  {
    slug: 'automation-on-a-budget',
    route: '/blog/automation-on-a-budget',
    title: 'Automation on a Budget: How Small Businesses Save 20+ Hours a Month for Under $20 — Borne Systems Blog',
    excerpt: 'Most service business owners think automation is something they have to grow into. They do not. Five small workflows, set up well and maintained quarterly, can reclaim 20+ hours a month for under $20. Here is the stack, the order to build it, and how to keep it running.',
    tag: 'Operational Efficiency',
    date: '2026-08-04',
    kind: 'post',
  },
  {
    slug: 'ai-automation-handoff-gap',
    route: '/blog/ai-automation-handoff-gap',
    title: 'The Handoff Gap: Where AI Automation Fails Small Service Businesses — Borne Systems Blog',
    excerpt: 'AI can capture the lead and still lose the job if the handoff is weak. Here is how service businesses close the gap between faster response, cleaner ownership, and booked revenue.',
    tag: 'AI Maintenance',
    date: '2026-08-04',
    kind: 'post',
  },
  {
    slug: 'lead-capture-system-out-of-date',
    route: '/blog/lead-capture-system-out-of-date',
    title: 'When Your Lead Capture System Gets Out of Date — Borne Systems Blog',
    excerpt: 'Lead capture systems do not usually fail all at once. They get stale as your hours, pricing, service area, and team handoffs change. Here is the quarterly review that keeps leads from leaking out.',
    tag: 'Lead Capture Maintenance',
    date: '2026-07-07',
    kind: 'post',
  },
  {
    slug: 'repeat-customer-math-reactivation-vs-new-leads',
    route: '/blog/repeat-customer-math-reactivation-vs-new-leads',
    title: 'The Repeat Customer Math: Why Reactivation Beats New Lead Generation — Borne Systems Blog',
    excerpt: 'Most service businesses spend heavily on new leads while their past customers quietly drift away. Here is why reactivation beats new lead generation on cost, speed, and lifetime value, and how to set it up in a week.',
    tag: 'Operational Efficiency',
    date: '2026-07-14',
    kind: 'post',
  },
  {
    slug: 'operational-fragmentation-hidden-tax',
    route: '/blog/operational-fragmentation-hidden-tax',
    title: 'The Hidden Tax: How Operational Fragmentation Is Quietly Bleeding Your Business Dry',
    excerpt: 'Most small service businesses run on a patchwork of disconnected tools. Every gap between those tools is a place where money quietly leaks out of your business. Here is how to find it and fix it.',
    tag: 'Operational Efficiency',
    date: '2026-06-09',
    kind: 'post',
  },
  {
    slug: 'small-business-survival-guide-2026',
    route: '/blog/small-business-survival-guide-2026',
    title: 'Small Business Survival Guide 2026: 3 Financial Levers to Pull Before Cash Flow Gets Tight',
    excerpt: 'Most small service businesses fail not from lack of work, but lack of cash at the wrong time. Here are the three financial levers that make the most difference in 2026.',
    tag: 'Operational Efficiency',
    date: '2026-06-09',
    kind: 'post',
  },
  {
    slug: 'the-15-minute-window',
    route: '/blog/the-15-minute-window',
    title: 'The 15-Minute Window: How Home Services Companies Lose Jobs Before Picking Up the Phone',
    excerpt: 'Every missed call is a job you will never get. In home services, the window to act is far shorter than most owners realize. Here is what 15 minutes is costing your business.',
    tag: 'Lead Capture',
    date: '2026-05-20',
    kind: 'post',
  },
  {
    slug: 'automation-drift-silent-revenue-leak',
    route: '/blog/automation-drift-silent-revenue-leak',
    title: 'Why Your Automation Quietly Stopped Working — And What It Is Costing You',
    excerpt: 'Automation does not break. It drifts. And most businesses do not notice until they have quietly lost six months of revenue. Here is the maintenance gap that is probably costing you right now.',
    tag: 'Maintenance',
    date: '2026-05-08',
    kind: 'post',
  },
  {
    slug: 'your-website-is-a-24-7-lead-machine',
    route: '/blog/your-website-is-a-24-7-lead-machine',
    title: "Your Website Is a 24/7 Lead Machine You're Only Using Half of",
    excerpt: 'Most service business websites go dark after 5pm. Here is what a real 24/7 lead capture system looks like and how to build one this month.',
    tag: 'Lead Capture',
    date: '2026-06-02',
    kind: 'post',
  },
];
